9

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -41,7 +41,13 @@ jobs:
     - name: Generate PDF
       run: |
         Rscript -e "bookdown::render_book('index.Rmd', 'bookdown::pdf_book')"
-        mv tesis.pdf docs/
+        if [ -f "tesis.pdf" ]; then
+          mv tesis.pdf docs/
+        else
+          echo "tesis.pdf not found"
+          exit 1
+        fi
+
 
     - name: Deploy to GitHub Pages
       uses: peaceiris/actions-gh-pages@v3
